// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// generate_ER_graph
Rcpp::NumericMatrix generate_ER_graph(const double lambda, const int nVertices, const int rseed);
RcppExport SEXP looplets_generate_ER_graph(SEXP lambdaSEXP, SEXP nVerticesSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type nVertices(nVerticesSEXP);
    Rcpp::traits::input_parameter< const int >::type rseed(rseedSEXP);
    __result = Rcpp::wrap(generate_ER_graph(lambda, nVertices, rseed));
    return __result;
END_RCPP
}
// decompose_graph_into_loops
Rcpp::NumericMatrix decompose_graph_into_loops(Rcpp::NumericMatrix edgeList, const int maxLoopLength);
RcppExport SEXP looplets_decompose_graph_into_loops(SEXP edgeListSEXP, SEXP maxLoopLengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edgeList(edgeListSEXP);
    Rcpp::traits::input_parameter< const int >::type maxLoopLength(maxLoopLengthSEXP);
    __result = Rcpp::wrap(decompose_graph_into_loops(edgeList, maxLoopLength));
    return __result;
END_RCPP
}
