# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_ER_graph <- function(lambda, nVertices, rseed = 1L) {
    .Call('looplets_generate_ER_graph', PACKAGE = 'looplets', lambda, nVertices, rseed)
}

decompose_graph_into_loops <- function(edgeList, maxLoopLength = 10L) {
    .Call('looplets_decompose_graph_into_loops', PACKAGE = 'looplets', edgeList, maxLoopLength)
}

